---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/drivers":
    get:
      summary: Fetches all drivers
      tags:
      - Drivers
      responses:
        '200':
          description: successful
    post:
      summary: Create new driver
      tags:
      - Drivers
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                home_address:
                  type: string
              required:
              - home_address
  "/api/drivers/{driver_id}/rides":
    get:
      summary: Get rides data per user
      tags:
      - Rides
      parameters:
      - name: driver_id
        in: path
        required: true
        description: ID of the driver
        schema:
          type: string
      responses:
        '200':
          description: rides data
    post:
      summary: Create a new ride for a user
      tags:
      - Rides
      parameters:
      - name: driver_id
        in: path
        required: true
        description: ID of the driver
        schema:
          type: string
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                start_address:
                  type: string
                destination_address:
                  type: string
              required:
              - start_address
              - destination_address
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
